### ISSUE TITLE
I want to maintain this project

### ISSUE THREAD

**Issue by erkanarslan** [rhanb/nativescript-fancy-calendar#11]
Even though nativescript pro ui is free now I still need this plugin. Because of that I want to maintain it, fix the bugs, make it more developer friendly. Would you add me as a contributor or transfer the repo to me?

**Comment by rhanb** [comment]
I'd be glad to, but at least make a PR first.

**Comment by erkanarslan** [comment]
@rhanb  Thanks. I will make PRs as soon as I finish them.

**Comment by mickaeleuranie** [comment]
I did some changes to programmatically select/unselect date and get same date format from Android and iOS for one of my project. I can commit them and make a PR if you want help, I like this project too (I didn't try the Nativescript Pro UI yet)

**Comment by rhanb** [comment]
sure @mickaeleuranie , I won't commit time coding on this project but I can definitely spend time accepting PR and add collaborators
