### ISSUE TITLE
ui/core/proxy not found

### ISSUE THREAD

**Issue by pagyx93** [rhanb/nativescript-fancy-calendar#2]
Hi, I cannot use your plugin because in nativescript-angular v3.0 the module ui/core/proxy has been removed.
How can i fix that?

**Comment by rhanb** [comment]
Hey there,

Effectively this plugin doesn't support {N} 3.0 yet, you can make a PR to contribute to this plugin or wait until i've got time (in a week it should be done)!

😄

**Comment by delosssh** [comment]
is selected date range available?  If not, any plan to add this feature?

**Comment by pagyx93** [comment]
Thanks for reply, I'll attend, for many reasons I'm also evaluating to downgrade or create a new project that use tns-core-modules version 2.5, anyone know how I can do that?

**Comment by rhanb** [comment]
Hi @pagyx93 , to downgrade to 2.5 follow this instructions: http://fluentreports.com/blog/?p=509
Hi @delosssh , date range selection is not available yet but will be coming in next versions but my priority are to make it work on 3.0 first and to stabilise this plugin then I will make more features 😄

**Comment by pagyx93** [comment]
Thank you I did that yesterday! Close that when plugin is 3.0 compatible

Have a nice day

**Comment by rhanb** [comment]
Support for {N} 3.0 is out:

- `rm -rf platforms`
- `tns remove nativescript-fancy-calendar && tns add nativescript-fancy-calendar`
