### ISSUE TITLE
How to use this on nativescript non angular .

### ISSUE THREAD

**Issue by ghost** [rhanb/nativescript-fancy-calendar#3]
Can you describe how to use this plugin without angular please, thank you.

**Comment by rhanb** [comment]
Hi, it will come soon ! But feel free to submit a PR if you'd like to implement it 😄

**Comment by ghost** [comment]
I have solved it , I will make a demo and pull request for you with a sample

**Comment by dpdragnev** [comment]
Hi @Feather-CMS,  what did you have to do to accomplish that?  I am facing the same issue.
