### ISSUE TITLE
How to get selected date in date changed event

### ISSUE THREAD

**Issue by HemantSPawar** [rhanb/nativescript-fancy-calendar#4]
How to get selected date in date changed event as mentioned below.
it shows empty object if i log(event)

public dateSelected(event) {
        console.log('date selected');
    }

**Comment by rhanb** [comment]
You should be able to get the date value through: 

```typescript
public dateSelected(event) {
    console.dir(event.data);
}
```

**Comment by HemantSPawar** [comment]
tx @rhanbIT  for quick reply......revert back soon

**Comment by HemantSPawar** [comment]
i dont know whats going wrong here....im getting empty object when i console.dir (event.data);
output/-
{\"date\":{},\"selected\":true}
