### ISSUE TITLE
How to highlight multiple dates

### ISSUE THREAD

**Issue by HemantSPawar** [rhanb/nativescript-fancy-calendar#5]
How to highlight multiple dates

i want to highlight attendance of employees in calendar view.there's no public method to do that work
i dnt know whats the way..

plz give it a direction

**Comment by rhanb** [comment]
Hi,

```typescript
this.settings = <Settings>{
        selectionMode: SELECTION_MODE.MULTIPLE
};
```

This is for enabling multiple date selection at once. 

If you talk about events (Dots) this is the way:

```typescript
this.events = new Array<CalendarEvent>(new CalendarEvent(new Date()), new CalendarEvent(new Date()), new CalendarEvent(temp));
```

**Comment by HemantSPawar** [comment]
yes its working fine but im talking about circle highlight like today.

**Comment by HemantSPawar** [comment]
Got solution:
just make addDecoratorToday as public method in Calendar.ts 

write these lines inside CalendarLoaded(event) method

 this._calendar = <Calendar>event.object;
   var date1= new Date(Date.parse("2017/02/10"));
   this._calendar.addDecoratorToday(date1, "Green", "Green", 25);
   var date2= new Date(Date.parse("2017/02/11"));
    this._calendar.addDecoratorToday(date2, "Red", "Red", 25);



somebody definitely need it
tx fancycalendar:)

**Comment by rhanb** [comment]
Hi @HemantSPawar ,

Thanks for your feedback didn't get what you meant ! I will add this feature in future release 👍

**Comment by HemantSPawar** [comment]
Im highlighting multiple dates .Tx
