### ISSUE TITLE
Can you please make `maximumDate` & `minimumDate` optional?

### ISSUE THREAD

**Issue by jogboms** [rhanb/nativescript-fancy-calendar#6]
First of all, I love your plugin, I have been using it for a while now and it's great but having to set a Date property for both those fields I feel, should be optional.

What do you think?

**Comment by rhanb** [comment]
Hi @jogboms ,

Thanks happy to see people using my plugins! They are you don't have to put a `maximumDate`and a `minimumDate` 😄
