### ISSUE TITLE
How to get selected date?

### ISSUE THREAD

**Issue by Alex1000A** [rhanb/nativescript-fancy-calendar#7]
Hi there, cool plugin ! .I just wondering why cannot get the date from method dateSelected. 
this is the result i get 
{"eventName":"dateSelected","object":{},"data":{"date":{},"selected":true}}

**Comment by rhanb** [comment]
@Alex1000A this is a bug it's not normal 😄 

This issue occured on Android AND/OR iOS ? 
Give as much informations about the bug as you can please !

**Comment by Alex1000A** [comment]
hi rhanb,it was in android platform and hope you can get more detail from my code 
http://plnkr.co/edit/jFzEwCgFfpfDVSYqCOMd?p=info

**Comment by rhanb** [comment]
Will try this out asap

**Comment by giorgiopiatti** [comment]
@rhanb I've give a rapid reading of your code and I see that MaterialCalendarOnDateSelectedListener return a date in this formula CalendarDay{2017-7-11}, can we use instead the ISO string. Keep the code close to standards is better for not continuously converting things.  

This plugin is very great, keep working on!

**Comment by rhanb** [comment]
@giorgiopiatti , thanks for pointing that out, it will help me fix this issue. 
Since I'm using third party library, I didn't bother with the format of dates that they were returning. I will implement a parser to have consistent date format for both platforms!

Cheers 😄

**Comment by rhanb** [comment]
Since last week the official NativeScript UI Pro is free, I advise you to switch to their calendar plugin which you can find here:

https://www.npmjs.com/package/nativescript-pro-ui

Cheers :)
